language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run test
  - |
    if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
      npm run report;
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
